# Generated by Django 4.2.4 on 2023-08-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="comment_id",
            new_name="answer_id",
        ),
    ]
